auction/urls.py
from django.conf.urls.static import static
from auction import settings
from django.urls import path, include

urlpatterns = [
    path('main', include('main.urls')),
    path('accounts', include('accounts.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
	path('', views.main, name = 'main'),
    path('/item_make', views.item_make, name = 'item_make'),
    path('/item_list', views.item_list, name = 'item_list'),
    path('/item_entry_list', views.item_entry_list, name = 'item_entry_list'),
    path('/item_mine_list', views.item_mine_list, name = 'item_mine_list'),
    path('/item_entry', views.item_entry, name = 'item_entry'),
    path('/item_detail/<int:item_id>', views.item_detail, name = 'item_detail')
]

main/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=64)

    class Meta:
        db_table = 'categories'

class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=64)
    start_price = models.DecimalField(max_digits=20, decimal_places=2, validators=[MinValueValidator(1)])
    expire_date = models.DateField(auto_now_add=True)
    is_expired = models.BooleanField(default=False)
    
    class Meta:
        db_table = 'items'

class Item_Image(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name = 'item_image')
    image = models.FileField(upload_to="item_images")
    
    class Meta:
      db_table = 'item_images'

class Item_Entry(models.Model):
    item = models.ForeignKey('main.Item', on_delete = models.CASCADE, related_name = 'item_entry')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=20, decimal_places=2, validators=[MinValueValidator(1)])
    entered_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'item_entries'

main/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator

class ItemEntryForm(forms.Form):
    item_name = forms.CharField(label = '제목 (64자 이하)', max_length=64)
    expire_date = forms.DateField(label = '만료 날짜')

main/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.db.models import Avg, Count, Q, Value, CharField, Func
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.db.models.functions import Concat

from .models import Item, Item_Image, Item_Entry
from .forms import ItemEntryForm

from datetime import datetime, date

class Round(Func):
    function = 'ROUND'
    template='%(function)s(%(expressions)s, 0)'
	
def main(request):
	return render(request, 'index.html', {})

def item_make(request):
	if request.user.is_authenticated:
		if request.method == 'POST':
			form = ItemEntryForm(request.POST)

			if form.is_valid():
				user_id = User.objects.get(id = request.user.id).id
				item = Item(
					name = form.data['item_name'],
					start_price = int(request.POST['price'].replace(",", "")),
					expire_date = request.POST['expire_date'],
					category_id = 1,
					is_expired = False,
					user_id = user_id,
				)
				item.save()
				
				item_image = Item_Image(
					item_id = item.id,
					image = request.FILES['image']
                )
				item_image.save()

				messages.info(request, "상품 정보가 등록되었습니다.")
				return redirect('main:main')

			else :
				messages.warning(request, "작성 폼을 올바르게 입력 하였는지 다시 한번 확인해 주세요.")
				return redirect('main:item_make')

		else: #GET일때
			form = ItemEntryForm()
			return render(request, 'item/item_make.html', {'form' : form})

	else: #로그인 안했을때
		messages.warning(request, "로그인 창으로 이동합니다.")
		return redirect('accounts:login')

def item_list(request):
    date_now = date(datetime.now().year, datetime.now().month, datetime.now().day)
    item_filter = Item.objects.filter(is_expired = False, expire_date__gte = date_now).prefetch_related("item_image")
    items = []
    for item in item_filter:
        image = Item_Image.objects.get(item_id = item.id)
        if Item_Entry.objects.filter(item_id = item.id).exists():
            entry = Item_Entry.objects.filter(item_id=item.id).order_by('-price')[0]
            items.append({
                 "id" : item.id,
                 "name" : item.name,
                 "start_price" : item.start_price,
                 "expire_date" : item.expire_date,
                 "highest_price" : entry.price,
                 "image" : image.image
            })
        else:
            items.append({
                 "id" : item.id,
                 "name" : item.name,
                 "start_price" : item.start_price,
                 "expire_date" : item.expire_date,
                 "highest_price" : 0,
                 "image" : image.image
                 })
    return render(request, 'item/item_list.html', {'items' : items})

def item_detail(request, item_id):
    item_filter = Item.objects.filter(id = item_id).prefetch_related("item_image")
    items = []
    for item in item_filter:
        image = Item_Image.objects.get(item_id = item.id)
        if Item_Entry.objects.filter(item_id = item.id).exists():
            entry = Item_Entry.objects.filter(item_id=item.id).order_by('-price')[0]
            items.append({
                 "id" : item.id,
                 "name" : item.name,
                 "start_price" : item.start_price,
                 "expire_date" : item.expire_date,
                 "highest_price" : entry.price,
                 "image" : image.image
            })
        else:
            items.append({
                 "id" : item.id,
                 "name" : item.name,
                 "start_price" : item.start_price,
                 "expire_date" : item.expire_date,
                 "highest_price" : 0,
                 "image" : image.image
                 })
    return render(request, 'item/item_detail.html', {'items' : items})

def item_entry(request):
    date_now = date(datetime.now().year, datetime.now().month, datetime.now().day)
    if request.user.is_authenticated:
        if request.method == 'POST':
            user_id = request.user.id
            item_id = request.POST['item_id']

            try:
                item = Item.objects.get(id=item_id)
                if item.user_id == user_id:
                    messages.warning(request, '본인 상품에는 입찰이 불가능합니다.')
                    return redirect(request.META.get('HTTP_REFERER', 'main:main'))
                
                elif item.expire_date < date_now:
                    messages.warning(request, '마감시한이 지나서 입찰이 불가능합니다.')
                    return redirect(request.META.get('HTTP_REFERER', 'main:main'))
                
                elif item.start_price >= int(request.POST['price'].replace(",", "")):
                    messages.warning(request, '최소 가격보다 높게 입찰해야 합니다.')
                    return redirect(request.META.get('HTTP_REFERER', 'main:main'))
                    
                elif Item_Entry.objects.filter(item_id = item_id):#다른사람 입찰 있을때
                    entry = Item_Entry.objects.filter(item_id=item.id).order_by('-price')[0]
                    if entry.price >= int(request.POST['price'].replace(",", "")):
                        messages.warning(request, '최고가보다 낮은 가격으로 입찰 할 수 없습니다')
                        return redirect(request.META.get('HTTP_REFERER', 'main:main'))
                    else:
                        if Item_Entry.objects.filter(user_id = user_id, item_id = item_id):
                            item = Item_Entry.objects.get(Q(user_id=user_id) & Q(item_id = item_id))

                            if item.price > int(request.POST['price'].replace(",", "")):
                                messages.warning(request, '낮은 가격으로 입찰 수정할 수 없습니다')
                                return redirect(request.META.get('HTTP_REFERER', 'main:main'))
                            Item_Entry.objects.filter(user_id = user_id, item_id = item_id).update(price=(request.POST['price'].replace(",", "")))
                            messages.success(request, '상품에 입찰하였습니다.')
                            return redirect('main:main')

                        else:
                            item_entry = Item_Entry(
                                user_id=user_id,
                                item_id=item_id,
                                price=int(request.POST['price'].replace(",", "")),
                                entered_date=date(datetime.now().year, datetime.now().month, datetime.now().day)
                            )
                            item_entry.save()
                            messages.success(request, '상품에 입찰하였습니다.')
                            return redirect('main:main')
                     
                elif Item_Entry.objects.filter(user_id = user_id, item_id = item_id):#다른사람 입찰x 사용자는 있을때
                    item = Item_Entry.objects.get(Q(user_id=user_id) & Q(item_id = item_id))

                    if item.price > int(request.POST['price'].replace(",", "")):
                        messages.warning(request, '낮은 가격으로 입찰 수정할 수 없습니다')
                        return redirect(request.META.get('HTTP_REFERER', 'main:main'))
                    Item_Entry.objects.filter(user_id = user_id, item_id = item_id).update(price=(request.POST['price'].replace(",", "")))
                    messages.success(request, '상품에 입찰하였습니다.')
                    return redirect('main:main')

                else:#사용자가 최초 입찰
                    item_entry = Item_Entry(
                        user_id=user_id,
                        item_id=item_id,
                        price=int(request.POST['price'].replace(",", "")),
                        entered_date=date(datetime.now().year, datetime.now().month, datetime.now().day)
                    )
                    item_entry.save()
                    messages.success(request, '상품에 입찰하였습니다.')
                return redirect('main:main')
                
            except Item.DoesNotExist:
                pass
    else:#비회원
        messages.warning(request, "로그인 창으로 이동합니다.")
        return redirect('accounts:login')
    
    return render(request, 'index.html')

def item_entry_list(request):
    items = Item_Entry.objects.filter(user_id = request.user.id)
    return render(request, 'item/item_entry_list.html', {'items' : items})

def item_mine_list(request):
    items = Item.objects.filter(user_id = request.user.id)
    return render(request, 'item/item_mine_list.html', {'items' : items})

main/templates/item/item_detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<head>
    <style>
    .item-container {
        display: flex;
        align-items: center;
        margin-bottom: 20px; /* 이미지와 정보 사이의 간격 조절 */
    }

    .thumbnail {
        max-width: 800px; /* 원하는 썸네일 최대 너비 설정 */
        max-height: 450px; /* 원하는 썸네일 최대 높이 설정 */
        margin-right: 20px; /* 이미지와 정보 사이의 간격 조절 */
    }

    .item-info {
        flex: 1; /* 남은 공간을 모두 차지하도록 설정 */
    }
    </style>
</head>
<body>
    <h1>상품 상세정보</h1>
    
    <ul>
        {% for item in items %}
            <li>
                <div class="item-container">
                    <img src="{{ item.image.url }}" alt="Item Image" class="thumbnail">
    
                    <div class="item-info">
                        <strong>상품 이름:</strong> {{ item.name }}<br>
                        <strong>시작 가격:</strong> {{ item.start_price }} / 
                        <strong>현재 입찰 최고가:</strong> {{ item.highest_price }}<br>
                        <strong>만료 일자:</strong> {{ item.expire_date }}<br>
    
                        <form method="POST" action="{% url 'main:item_entry' %}">
                            {% csrf_token %}
                            <input type="hidden" name="item_id" value="{{ item.id }}">
                            입찰 가격 : <input type="text" onkeyup="javascript:chnNum(this)" name="price" required><br>
                            <input type="submit" class="btn btn-primary" value="상품 입찰하기">
                        </form>
                        {% if messages %}
                            <ul class="messages">
                                {% for message in messages %}
                                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
    
</body>
</html>


{% endblock %}

main/templates/item/item_entry_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<body>
    <h1>내가 입찰한 상품 리스트</h1>
    
    <ul>
        {% for item in items %}
            <li>
                <div class="item-container">
                    <a href="{% url 'main:item_detail' item.id %}">
                    {% for image in item.item.item_image.all %}
                        <img src="{{ image.image.url }}" alt="Item Image" class="thumbnail">
                    {% endfor %}
                    <div class="item-info">
                    <a href="{% url 'main:item_detail' item.id %}">
                    <strong>상품 이름:</strong> {{ item.item.name }}<br></a>
                    <strong>내가입찰한 가격:</strong> {{ item.price }}<br>
                    <strong>만료 일자:</strong> {{ item.item.expire_date }}<br>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
</body>
</html>


{% endblock %}

main/templates/item/item_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<!DOCTYPE html>
<html lang="kr">
<head>
    <style>
        .item-container {
            display: inline-block;
            margin: 10px;
        }

        .thumbnail {
            width: 100px;
            height: 100px;
        }
    </style>
</head>
<body>
    <h1>상품 리스트</h1>

    <ul>
        {% for item in items %}
            {% if forloop.counter0|divisibleby:5 %}
                </ul><ul>
            {% endif %}
            <li>
                <div class="item-container">
                    <a href="{% url 'main:item_detail' item.id %}">
                        <img src="{{ item.image.url }}" alt="Item Image" class="thumbnail">
                    </a>
                    <div class="item-info">
                        <a href="{% url 'main:item_detail' item.id %}">
                            <strong>상품 이름:</strong> {{ item.name }}<br>
                        </a>
                        <strong>시작 가격:</strong> {{ item.start_price }} /
                        <strong>현재 입찰 최고가:</strong> {{ item.highest_price }}<br>
                        <strong>만료 일자:</strong> {{ item.expire_date }}<br>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
</body>
</html>



{% endblock %}

main/templates/item/item_make.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
{% load humanize %}

<div class="wrapper">
        <h1>작품 등록</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            제목 : {{ form.item_name }}<br>
            시작 가격 : <input type="text" onkeyup="javascript:chnNum(this)" name="price" required><br>
            만료 일자 : <input type="date" placeholder="연도,월,일" name="expire_date" value="{{date|date:'Y-m-d'}}" required><br>
            상품 사진 : <input type="file" name="image" accept=".jpg, .png, .jpeg" required><br>
            <input type="submit" class="btn btn-primary" value="상품 등록하기">
        </form>
</div>

{% endblock %}

main/templates/item/item_mine_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<body>
    <h1>내가 생성한 상품 리스트</h1>
    
    <ul>
        {% for item in items %}
            <li>
                <div class="item-container">
                    <a href="{% url 'main:item_detail' item.id %}">
                    {% for image in item.item_image.all %}
                        <img src="{{ image.image.url }}" alt="Item Image" class="thumbnail">
                    {% endfor %}
                    <div class="item-info">
                    <a href="{% url 'main:item_detail' item.id %}">
                    <strong>상품 이름:</strong> {{ item.name }}<br></a>
                    <strong>시작 가격:</strong> {{ item.start_price }}<br>
                    <strong>만료 일자:</strong> {{ item.expire_date }}<br>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
</body>
</html>


{% endblock %}