accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('/signup', signup, name='signup'),
    path('/login', login, name='login'),
    path('/logout', logout, name='logout'),
]

auction/urls.py
from django.conf.urls.static import static
from auction import settings
from django.urls import path, include

urlpatterns = [
    path('main', include('main.urls')),
    path('accounts', include('accounts.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
	path('', views.main, name = 'main'),
    path('/item_make', views.item_make, name = 'item_make'),
    path('/item_list', views.item_list, name = 'item_list'),
    path('/item_entry_list', views.item_entry_list, name = 'item_entry_list'),
    path('/item_mine_list', views.item_mine_list, name = 'item_mine_list'),
    path('/item_entry', views.item_entry, name = 'item_entry'),
    path('/item_detail/<int:item_id>', views.item_detail, name = 'item_detail')
]

templates/base.html
<!DOCTYPE html>
<html>
<head>
    {% include 'head.html' %}
</head>
<body>
    <div style="text-align: center;">
        {% if messages %}
            {% for message in messages %}
                <div class="alert {{ message.tags }} alert-auto-dismissible alert-dismissible notification-container text-center" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}

<h1>신난다 경매</h1>
    {% if user.is_authenticated %}
        {{user.username}}님 안녕하세요
        <a href = "{% url 'accounts:logout' %}"><button class = "btn btn-primary">로그아웃</button></a>
        <a href = "{% url 'main:item_make' %}"><button class = "btn btn-primary">상품 등록</button></a>
        <a href = "{% url 'main:item_list' %}"><button class = "btn btn-primary">상품 리스트</button></a>
        <a href = "{% url 'main:main' %}"><button class = "btn btn-primary">첫화면</button></a><br>
        <a href = "{% url 'main:item_entry_list' %}"><button class = "btn btn-primary">내가 입찰한 상품 리스트</button></a>
        <a href = "{% url 'main:item_mine_list' %}"><button class = "btn btn-primary">내가 생성한 상품 리스트</button></a> 

    {% else %}<!-- 로그인 안했을때 -->
        <a href = "{% url 'accounts:signup' %}"><button class = "btn btn-primary">회원가입</button></a>
        <a href = "{% url 'accounts:login' %}"><button class = "btn btn-primary">로그인</button></a>
        <a href = "{% url 'main:item_list' %}"><button class = "btn btn-primary">상품 리스트</button></a>
        <a href = "{% url 'main:main' %}"><button class = "btn btn-primary">첫화면</button></a><br> 
    {% endif %}
    <br><br>
    <script type="text/javascript">

        function chnNum(a) {
          let commaNumber = comma($(a).val());
          $(a).val(commaNumber);
        }
        
        function comma(num){
          let len, point, str; 
          num = num.replace(/[^0-9]/g,''); // 숫자가 아닌 문자는 전부 replace하여 숫자만 추출
          num = num.replace(/(^0+)/, "");      // 0으로 시작하는 첫자리 수는 제거
          
          //해당 숫자의 길이와 천단위 콤마를 찍을 위치값을 구해 콤마를 추가
          point = num.length % 3 ;
          len = num.length;
          str = num.substring(0, point); 
          
          while (point < len) { 
            if (str != "") str += ","; 
            str += num.substring(point, point + 3); 
            point += 3; 
          } 
        
          //결과값을 반환
          return str; 
        }
        
        </script>

{% block content %}

{% endblock %}
</body>
</html>

templates/head.html
<head>
  <title>Auction</title>

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <style>
  </style>

  <!-- bootstrap-->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  
</head>